package POJOS;
// Generated May 15, 2015 6:55:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matchmaker generated by hbm2java
 */
@Entity
@Table(name="matchmaker"
    ,catalog="donation"
)
public class Matchmaker  implements java.io.Serializable {


     private Integer matchmakerId;
     private Books books;
     private User user;
     private String donRec;
     private int quantity;
     private Set transactionsForDonorId = new HashSet(0);
     private Set transactionsForRecId = new HashSet(0);

    public Matchmaker() {
    }

	
    public Matchmaker(Books books, User user, String donRec, int quantity) {
        this.books = books;
        this.user = user;
        this.donRec = donRec;
        this.quantity = quantity;
    }
    public Matchmaker(Books books, User user, String donRec, int quantity, Set transactionsForDonorId, Set transactionsForRecId) {
       this.books = books;
       this.user = user;
       this.donRec = donRec;
       this.quantity = quantity;
       this.transactionsForDonorId = transactionsForDonorId;
       this.transactionsForRecId = transactionsForRecId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MatchmakerId", unique=true, nullable=false)
    public Integer getMatchmakerId() {
        return this.matchmakerId;
    }
    
    public void setMatchmakerId(Integer matchmakerId) {
        this.matchmakerId = matchmakerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BookId", nullable=false)
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="DonRec", nullable=false, length=45)
    public String getDonRec() {
        return this.donRec;
    }
    
    public void setDonRec(String donRec) {
        this.donRec = donRec;
    }

    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matchmakerByDonorId")
    public Set getTransactionsForDonorId() {
        return this.transactionsForDonorId;
    }
    
    public void setTransactionsForDonorId(Set transactionsForDonorId) {
        this.transactionsForDonorId = transactionsForDonorId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matchmakerByRecId")
    public Set getTransactionsForRecId() {
        return this.transactionsForRecId;
    }
    
    public void setTransactionsForRecId(Set transactionsForRecId) {
        this.transactionsForRecId = transactionsForRecId;
    }
}


