package Configur.saxx.POJOS;
// Generated May 15, 2015 9:51:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="donation"
)
public class User  implements java.io.Serializable {


     private int id;
     private String name;
     private byte[] organization;
     private String email;
     private String password;
     private String address;
     private String city;
     private String country;
     private byte[] verification;
     private Matchmaker matchmaker;

    public User() {
    }

	
    public User(int id, String name, byte[] organization, String email, String password, String city, String country, byte[] verification) {
        this.id = id;
        this.name = name;
        this.organization = organization;
        this.email = email;
        this.password = password;
        this.city = city;
        this.country = country;
        this.verification = verification;
    }
    public User(int id, String name, byte[] organization, String email, String password, String address, String city, String country, byte[] verification, Matchmaker matchmaker) {
       this.id = id;
       this.name = name;
       this.organization = organization;
       this.email = email;
       this.password = password;
       this.address = address;
       this.city = city;
       this.country = country;
       this.verification = verification;
       this.matchmaker = matchmaker;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Organization", nullable=false)
    public byte[] getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(byte[] organization) {
        this.organization = organization;
    }

    
    @Column(name="Email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="City", nullable=false, length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Country", nullable=false, length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="Verification", nullable=false)
    public byte[] getVerification() {
        return this.verification;
    }
    
    public void setVerification(byte[] verification) {
        this.verification = verification;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Matchmaker getMatchmaker() {
        return this.matchmaker;
    }
    
    public void setMatchmaker(Matchmaker matchmaker) {
        this.matchmaker = matchmaker;
    }




}


