package POJOS;
// Generated May 15, 2015 10:43:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name="books"
    ,catalog="donation"
)
public class Books  implements java.io.Serializable {


     private Integer bookId;
     private String bookName;
     private String author;
     private String class_;
     private String board;
     private String bookImage;
     private String bookDescription;
     private Set matchmakers = new HashSet(0);

    public Books() {
    }

	
    public Books(String bookName) {
        this.bookName = bookName;
    }
    public Books(String bookName, String author, String class_, String board, String bookImage, String bookDescription, Set matchmakers) {
       this.bookName = bookName;
       this.author = author;
       this.class_ = class_;
       this.board = board;
       this.bookImage = bookImage;
       this.bookDescription = bookDescription;
       this.matchmakers = matchmakers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BookId", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="BookName", nullable=false, length=45)
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    
    @Column(name="Author", length=45)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="Class", length=45)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="Board", length=45)
    public String getBoard() {
        return this.board;
    }
    
    public void setBoard(String board) {
        this.board = board;
    }

    
    @Column(name="BookImage", length=45)
    public String getBookImage() {
        return this.bookImage;
    }
    
    public void setBookImage(String bookImage) {
        this.bookImage = bookImage;
    }

    
    @Column(name="BookDescription", length=16777215)
    public String getBookDescription() {
        return this.bookDescription;
    }
    
    public void setBookDescription(String bookDescription) {
        this.bookDescription = bookDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="books")
    public Set getMatchmakers() {
        return this.matchmakers;
    }
    
    public void setMatchmakers(Set matchmakers) {
        this.matchmakers = matchmakers;
    }




}


